name: .NET Core Test & Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore NetVanguard.sln
      
    - name: Build
      run: dotnet build NetVanguard.sln --no-restore
      
    - name: Test Core
      run: dotnet test NetVanguard.Tests/NetVanguard.Tests.csproj --no-build --verbosity normal
